"""add questions_to_serve and attempt question_ids for exam pooling

Revision ID: 06c5195cf352
Revises: 2ede423ad1a5
Create Date: 2026-08-04 22:31:52.007585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06c5195cf352'
down_revision: Union[str, None] = '2ede423ad1a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_attempts', sa.Column('question_ids', sa.JSON(), nullable=True))
    op.add_column('exams', sa.Column('questions_to_serve', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'questions_to_serve')
    op.drop_column('exam_attempts', 'question_ids')
    # ### end Alembic commands ###
