"""add image_path to discussion posts

Revision ID: 14d2aaae395f
Revises: 6a650495cbbe
Create Date: 2026-08-05 00:42:17.614448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '14d2aaae395f'
down_revision: Union[str, None] = '6a650495cbbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion_posts', sa.Column('image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion_posts', 'image_path')
    # ### end Alembic commands ###
