"""drop unique constraint on password_reset_tokens.token for OTP reuse across users

Revision ID: 190165c36779
Revises: 9e6bdc017ab3
Create Date: 2026-08-02 22:25:28.818628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '190165c36779'
down_revision: Union[str, None] = '9e6bdc017ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_password_reset_tokens_token', table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_index('ix_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=True)
    # ### end Alembic commands ###
