"""add graded_detail to attempt_answers

Revision ID: 1d646160a43a
Revises: 2223f5186488
Create Date: 2026-07-29 23:21:07.554095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d646160a43a'
down_revision: Union[str, None] = '2223f5186488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt_answers', sa.Column('graded_detail', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt_answers', 'graded_detail')
    # ### end Alembic commands ###
