"""add coding question type and test cases

Revision ID: 2223f5186488
Revises: b673ea53ce34
Create Date: 2026-07-29 23:15:17.245551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2223f5186488'
down_revision: Union[str, None] = 'b673ea53ce34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic autogenerate doesn't detect added Postgres enum values; added manually.
    op.execute("ALTER TYPE question_type ADD VALUE IF NOT EXISTS 'coding'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('questions', sa.Column('starter_code', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'starter_code')
    op.drop_column('questions', 'languages')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
    # Note: Postgres doesn't support removing a value from an existing enum type
    # without recreating it; the 'coding' value is left in question_type on downgrade.
