"""require 5 puzzles per day for streak, unique per puzzle per day

Revision ID: 27924c03ab39
Revises: 06c5195cf352
Create Date: 2026-08-04 22:46:13.633471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27924c03ab39'
down_revision: Union[str, None] = '06c5195cf352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_puzzle_attempt_user_date', 'puzzle_attempts', type_='unique')
    op.create_unique_constraint('uq_puzzle_attempt_user_puzzle_date', 'puzzle_attempts', ['user_id', 'puzzle_id', 'solved_for_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_puzzle_attempt_user_puzzle_date', 'puzzle_attempts', type_='unique')
    op.create_unique_constraint('uq_puzzle_attempt_user_date', 'puzzle_attempts', ['user_id', 'solved_for_date'])
    # ### end Alembic commands ###
