"""add k8s level progress table

Revision ID: 30f68130e48e
Revises: c68e5fc6dd91
Create Date: 2026-08-04 23:55:49.667238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30f68130e48e'
down_revision: Union[str, None] = 'c68e5fc6dd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8s_level_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.String(length=50), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'level_id', name='uq_k8s_level_progress_user_level')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('k8s_level_progress')
    # ### end Alembic commands ###
