"""add section and department to users

Revision ID: 426cc0a3a948
Revises: cab6d2b246ce
Create Date: 2026-08-03 19:51:15.682949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '426cc0a3a948'
down_revision: Union[str, None] = 'cab6d2b246ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('section', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.drop_column('users', 'section')
    # ### end Alembic commands ###
