"""add question_reports table

Revision ID: 48097a35122f
Revises: f50545da2901
Create Date: 2026-08-01 21:37:09.591990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48097a35122f'
down_revision: Union[str, None] = 'f50545da2901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('wrong_answer', 'unclear_wording', 'typo', 'other', name='question_report_reason'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_reports')
    # ### end Alembic commands ###
