"""add roll_number to users

Revision ID: 5d8f7a371988
Revises: c4eacf17db11
Create Date: 2026-08-03 00:00:34.641531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d8f7a371988'
down_revision: Union[str, None] = 'c4eacf17db11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roll_number', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_roll_number'), 'users', ['roll_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_roll_number'), table_name='users')
    op.drop_column('users', 'roll_number')
    # ### end Alembic commands ###
