"""add phone_number location institution to users

Revision ID: 7e39c75cc0a3
Revises: 1d646160a43a
Create Date: 2026-08-01 20:20:00.787911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e39c75cc0a3'
down_revision: Union[str, None] = '1d646160a43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('institution', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'institution')
    op.drop_column('users', 'location')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
