"""add gender education_level avatar to users and subjects

Revision ID: b5d655eabf0f
Revises: 9e41644a793e
Create Date: 2026-08-05 21:24:38.875801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b5d655eabf0f'
down_revision: Union[str, None] = '9e41644a793e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


education_level_enum = sa.Enum('school', 'college', 'engineering', name='education_level')
gender_enum = sa.Enum('male', 'female', 'other', name='gender')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    education_level_enum.create(bind, checkfirst=True)
    gender_enum.create(bind, checkfirst=True)

    op.add_column('subjects', sa.Column('education_level', education_level_enum, nullable=True))
    op.add_column('users', sa.Column('gender', gender_enum, nullable=True))
    op.add_column('users', sa.Column('education_level', education_level_enum, nullable=True))
    op.add_column('users', sa.Column('avatar_id', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_users_education_level'), 'users', ['education_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_education_level'), table_name='users')
    op.drop_column('users', 'avatar_id')
    op.drop_column('users', 'education_level')
    op.drop_column('users', 'gender')
    op.drop_column('subjects', 'education_level')

    bind = op.get_bind()
    gender_enum.drop(bind, checkfirst=True)
    education_level_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
