"""add your_answer correct_answer to question_reports

Revision ID: b9a0b16a9442
Revises: 1a243a600b97
Create Date: 2026-08-02 02:57:16.719134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9a0b16a9442'
down_revision: Union[str, None] = '1a243a600b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_reports', sa.Column('your_answer', sa.Text(), nullable=True))
    op.add_column('question_reports', sa.Column('correct_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_reports', 'correct_answer')
    op.drop_column('question_reports', 'your_answer')
    # ### end Alembic commands ###
