"""add ai_radar_items table

Revision ID: ba1bec021425
Revises: b5d655eabf0f
Create Date: 2026-08-26 17:25:37.126411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba1bec021425'
down_revision: Union[str, None] = 'b5d655eabf0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_radar_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('query', sa.String(length=200), server_default='manual', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('use_cases', sa.Text(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_radar_items')
    # ### end Alembic commands ###
