"""add job_postings table

Revision ID: c4c1b8808979
Revises: 5d8f7a371988
Create Date: 2026-08-03 00:30:39.875573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4c1b8808979'
down_revision: Union[str, None] = '5d8f7a371988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_remote', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('min_qualification', sa.String(length=255), nullable=True),
    sa.Column('package', sa.String(length=100), nullable=True),
    sa.Column('application_link', sa.String(length=500), nullable=True),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_postings')
    # ### end Alembic commands ###
