"""add proctor_events table

Revision ID: f50545da2901
Revises: 7e39c75cc0a3
Create Date: 2026-08-01 21:18:12.140674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f50545da2901'
down_revision: Union[str, None] = '7e39c75cc0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proctor_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('tab_switch', 'fullscreen_exit', 'copy_attempt', 'paste_attempt', 'webcam_snapshot', name='proctor_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('snapshot_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proctor_events')
    # ### end Alembic commands ###
